/* Replace these sample entries with your own writing, projects and links. */
window.journalContent = {
 places: [
  {id:'monastery',name:'Monastery',category:'Learning',icon:'♜',x:46.5,y:25, description:'A quiet place to stay curious.',intro:'Books, ideas, and lessons collected along the way.',items:[{title:'Things I’m learning',type:'Learning journal',body:'This shelf is waiting for your reading notes, courses, and discoveries. Add the ideas that changed how you see the world.'},{title:'A beginner, again',type:'Sample reflection',body:'There is something freeing about starting from the beginning. When we stop trying to look like experts, we make room to notice what is really there.'}]},
  {id:'trail',name:'Forest Cabin',category:'Life & photography',icon:'♠',x:77.8,y:29,description:'The long way is sometimes the best way.',intro:'Small observations from outside the studio.',items:[{title:'A walk with no destination',type:'Sample field note',body:'Some walks do not need to lead anywhere. The rustle of leaves beside the path, a new leaf, the light changing over a familiar ridge. A few things worth keeping.'},{title:'Through the viewfinder',type:'Photography · coming soon',body:'Your photographs will live here. A place for landscapes, everyday moments, and the details that ask you to stop and look.'}]},
  {id:'tea',name:'Tea House',category:'Writing',icon:'♨',x:38.4,y:54.5,description:'A cup of tea. A few things on my mind.'},
  {id:'studio',name:'Design Studio',category:'Selected work',icon:'▣',x:66.5,y:47.3,description:'Where questions become things you can use.',intro:'A home for design stories, decisions, and the work behind the work.',items:[{title:'A project, from question to craft',type:'Case study · placeholder',body:'Add a real project here: the problem you set out to solve, your role, the decisions you made, and what changed. Images and links can be added alongside the story.'},{title:'How I approach design',type:'Practice · placeholder',body:'Use this space to share your process in your own words. What do you notice first? What questions do you ask? What makes something feel finished?'}]},
  {id:'projects',name:'Greenhouse',category:'Projects & experiments',icon:'⚘',x:85.6,y:58.6,description:'Small ideas, given room to grow.',intro:'A place for side projects, prototypes, and unfinished possibilities.',items:[{title:'This little mountain village',type:'Interactive experiment',body:'A personal portfolio imagined as an explorable world. Different places hold different pieces of a life: writing, design, curiosity, and the things in between.'},{title:'Something taking root',type:'Project slot · placeholder',body:'What are you making just because you want to see it exist? Give it a name, a short story, and a link here.'}]},
  {id:'skills',name:'The Workshop',category:'My toolkit',icon:'⚙',x:92.3,y:75,description:'A few well-used tools.',intro:'A shelf for the skills and methods behind your work.',items:[{title:'Design & making',type:'Toolkit · placeholder',body:'Add the tools and skills you actually use, with a little context about what you make with each one.'},{title:'Working together',type:'Approach · placeholder',body:'Share how you collaborate, give feedback, and turn a group of people into a team.'}]},
  {id:'contact',name:'Post Office',category:'Say hello',icon:'✉',x:92.4,y:83.7,description:'Good conversations start with hello.',intro:'A small post office at the end of the trail.',items:[]}
 ],
 writings:[
  {id:'attention',shelf:'essays',title:'The art of paying attention',type:'Sample essay',time:'2 min',body:['Most days, the interesting things are not the loudest things. They are the light moving across a wall, the pause before an answer, the little workaround someone has invented for a tool that doesn’t quite fit.','Paying attention is a kind of practice. It asks us to slow down long enough to see what is already here, before rushing to decide what ought to be.','This is a sample piece for the tea house. Replace it with a story, thought, or essay of your own.']},
  {id:'home',shelf:'essays',title:'What we carry from home',type:'Sample reflection',time:'2 min',body:['A place can stay with us long after we leave it. Sometimes it is a smell, a way of making tea, or a certain shade of green after rain.','Perhaps the places we come from become part of how we make things. A preference for quiet. A respect for the difficult path. A wish to leave a little room for someone else.','This is a sample reflection, ready for your own words.']},
  {id:'unfinished',shelf:'notes',title:'Permission to be unfinished',type:'Sample note',time:'1 min',body:['A notebook is useful because it lets a thought exist before it is ready. A sketch, a crossed-out sentence, a question without an answer.','This village can be a notebook too. A place that changes as life does.','This is sample writing. Your real notes will go here.']},
  {id:'slower',shelf:'notes',title:'Taking the slower path',type:'Sample note',time:'1 min',body:['There is a shortcut up the hill, and there is the path that winds through the trees. Not every day needs to be a shortcut day.','A small sample note for a quiet afternoon. Replace it with something you noticed along the way.']}
 ],
 contactEmail:''
};
