/* Real project and photography collections assembled from the user-provided portfolio folder. */
window.villageCollection = {
 projects: [
  {id:'lakshadweep',group:'work',title:'Lakshadweep Ship Ticketing',category:'Public transport',year:'2025',label:'Selected work',image:'portfolio/lakshadweep.webp',summary:'Designing clarity and trust for a public transport system used by islanders, families, and operational teams.',role:'Product design',format:'Web & mobile',url:'https://lakshadweep.irctc.co.in/',question:'How can a public ticketing ecosystem feel clear and trustworthy under real-world constraints?',intro:'The Lakshadweep ticketing platform sits inside a larger operational system. The experience needs to serve travelers while respecting the people and processes that keep island transport moving.',decisions:[['Serve the whole journey','The work considers islanders, families, and operational teams rather than treating booking as an isolated screen.'],['Make critical information clear','A public transport product has to make choices, status, and next steps understandable without adding uncertainty.'],['Design for real conditions','Web and mobile experiences need to remain useful within the practical constraints of island travel and operations.']],reflection:'This project represents the kind of high-stakes system work I care about: products where small decisions can make a public service easier to understand and trust.'},
  {id:'karnataka',group:'work',title:'Karnataka Tourism',category:'Public platform',year:'2025',label:'Selected work',image:'portfolio/karnataka.webp',summary:'Redesigning a high-volume tourism website for clarity, information, and trust.',role:'Product design',format:'Web',url:'https://karnatakatourism.org/',question:'How can a large public tourism platform help many kinds of visitors find useful information with confidence?',intro:'Karnataka Tourism brings destinations, stories, and practical travel information into one public platform. The redesign focused on making a large information space easier to understand and explore.',decisions:[['Create clearer paths','The platform needs legible routes through a large amount of tourism information.'],['Support discovery','Destinations and stories should invite exploration without making practical information harder to find.'],['Build public trust','A high-volume official platform has to feel coherent, dependable, and ready for many different visitors.']],reflection:'The project reinforced that information architecture and visual clarity are inseparable when a public platform has to serve both inspiration and planning.'},
  {id:'food-on-track',group:'work',title:'IRCTC Food On Track',category:'Travel service',year:'2025',label:'Selected work',image:'portfolio/food-on-track.webp',summary:'Improving discoverability, clarity, and scale for a high-traffic food-ordering service.',role:'Product design',format:'Mobile app',url:'https://play.google.com/store/apps/details?id=com.irctc.fot&pcampaignid=web_share',question:'How can ordering food during a train journey feel straightforward for a broad and diverse group of travelers?',intro:'Food On Track is a high-traffic public service used in the changing context of a train journey. The redesign focused on helping people understand what is available and move through ordering with less friction.',decisions:[['Improve discoverability','The first task is helping travelers understand what they can order and where the service fits into their journey.'],['Keep the flow legible','Clear choices and next steps matter when people may be distracted, moving, or working with limited time.'],['Design for scale','The experience has to support diverse users and a large public service without becoming visually or operationally confusing.']],reflection:'The work strengthened my interest in systems where clarity is more than polish—it directly affects whether a service feels usable.'},

  {id:'mapthis',group:'personal',title:'Mapthis.xyz',category:'Mapping experiment',year:'01',label:'Personal project',image:'portfolio/mapthis.webp',summary:'A small mapping experiment built to make places easier to explore and share.',role:'Concept & product design',format:'Live web experiment',url:'https://mapthis.xyz/',question:'What new interactions become possible when a map is treated as a creative surface?',intro:'Mapthis.xyz is one of a series of small products built to turn an idea into something tangible and testable.',decisions:[['Start with the map','The map remains the central object instead of becoming decoration around a conventional interface.'],['Ship the experiment','A working public version creates clearer feedback than an idea left in a file.'],['Keep the route direct','The experience stays focused on the core mapping interaction.']],reflection:'This is part of an ongoing practice of building small products to learn through use.'},
  {id:'kalm',group:'personal',title:'KALM AI',category:'Hackathon project',year:'02',label:'Working prototype',image:'portfolio/kalm.webp',summary:'A local-first ambient workplace companion for posture, eye care, movement, and calmer work rhythms.',role:'Product concept, experience & prototype',format:'Electron, React, sensors & e-paper',url:'https://kalm-ai-presentation.rhyhn.chatgpt.site/',question:'How might workplace wellbeing guidance stay calm, private, and useful instead of becoming another demanding dashboard?',intro:'KALM combines local camera posture trends, timed eye care, and optional ESP32 desk telemetry into one restrained work-rhythm state. Persistent coaching actions can also appear on a small e-paper display.',decisions:[['Keep sensitive processing local','Camera and desk signals are handled locally, with frames and continuous vital history excluded from storage.'],['Coach only when useful','Comfort, movement, and eye-care prompts use persistence, cooldowns, recovery detection, and humane limits rather than constant alerts.'],['Let hardware fade into the environment','The e-paper display carries concise advice while the desktop experience provides consent, calibration, context, and detail.']],reflection:'The prototype was designed as an end-to-end system: onboarding, calibration, live coaching, recovery, progression, local persistence, hardware simulation, and a desktop package.'},
  {id:'anagram-2048',group:'personal',title:'Anagram 2048',category:'Word game',year:'03',label:'Personal project',image:'portfolio/anagram-2048.webp',summary:'A compact word-and-number game experiment inspired by the rhythm of 2048.',role:'Concept & interaction',format:'Live web game',url:'https://anagram2048.netlify.app/',question:'Can a familiar puzzle rhythm become the foundation for a different kind of word game?',intro:'Anagram 2048 explores how a recognizable interaction model can be remixed into a playful, self-contained experience.',decisions:[['Use a familiar rhythm','The interaction borrows a pattern people can understand quickly.'],['Change the mental task','Word play shifts the challenge away from pure number combination.'],['Keep it immediately playable','The experiment is published as a direct web experience with very little ceremony.']],reflection:'Small games are useful design exercises because every interaction has to earn its place.'},
  {id:'meridian',group:'personal',title:'Meridian',category:'Generative music',year:'04',label:'Makeathon experiment',image:'portfolio/meridian.webp',summary:'A world map where every pin creates a different generative soundscape.',role:'Concept, product & interaction',format:'Live web experiment',url:'https://meridian-app.netlify.app/',question:'What if a map could play music shaped by the exact place you choose?',intro:'Meridian responds to coordinates, elevation, biome, cultural context, and atmosphere. Drop a pin anywhere—from a city to an unnamed point in the Pacific—and the system turns that place into a sonic palette.',decisions:[['Drop a pin','The map makes the input spatial and immediate: choosing a place is the main interaction.'],['Let AI read the location','Geographic and cultural signals are synthesized before a note is generated.'],['Generate something singular','The result is an original, non-repeating ambient composition rather than a playlist tied to a city.']],reflection:'Meridian began as a Makeathon experiment around one thought: music has geography, while playlists usually do not.'},
  {id:'window',group:'personal',title:'View From My Window',category:'Visual journal',year:'05',label:'Personal project',image:'portfolio/view-from-window.webp',summary:'A quiet visual experiment about looking outward from an everyday place.',role:'Concept & visual design',format:'Framer site',url:'https://mywindow.framer.wiki/',question:'How much of a place can be held in one repeated view?',intro:'A small visual project that treats an ordinary window as a frame for noticing time, weather, and change.',decisions:[['Begin with one frame','A limited point of view gives the project its identity.'],['Let change carry the story','Light, weather, and passing detail create variation.'],['Keep the presentation quiet','The site gives the images space rather than wrapping them in a heavy interface.']],reflection:'Not every project needs a complex system. Sometimes the practice is simply learning to look again.'},
  {id:'lost-in-color',group:'personal',title:'Lost in Color',category:'Accessibility game',year:'06',label:'Personal project',image:'portfolio/lost-in-color.webp',summary:'A game that simulates three kinds of color blindness and tests how well your vision holds up.',role:'Concept, design & build',format:'Progressive web app',url:'https://lostincolor.fun/',question:'Can a short game make differences in color perception easier to experience and discuss?',intro:'Originally made for a Figma Makeathon and later rebuilt as a progressive web app, Lost in Color turns color perception into an interactive challenge.',decisions:[['Make the difference experiential','The game lets players encounter simulated color-vision conditions through play.'],['Use three simulations','Distinct modes make the experience more specific than a single generic filter.'],['Rebuild it as a PWA','The later version makes the experiment easier to revisit and share as a standalone product.']],reflection:'The project combines accessibility, game mechanics, and the satisfaction of taking an old experiment further.'},
  {id:'sainoo',group:'personal',title:'Sainoo',category:'Service concept',year:'07',label:'Working concept',image:'portfolio/sainoo.png',summary:'A considered introductions service for people who call Sikkim home—and the people close to them.',role:'Product thesis, research plan & pitch',format:'Service concept',question:'How might serious introductions feel private, local, thoughtful, and centred on the people being introduced?',intro:'Sainoo begins from the belief that marriage conversations in Sikkim move through home, friendship, distance, and trust—not through a public catalogue.',decisions:[['Interest first, introductions second','The proposed service starts with an invitation and a considered conversation before any introduction is made.'],['Consent stays central','Family can be involved, but no detail moves forward without permission and the person remains at the centre.'],['Learn before building','The first 90 days focus on listening, running a small human-led circle, and using evidence to define the product people actually need.']],reflection:'The early model is deliberately narrow: build a trusted network and a careful service before deciding what should become software.'},
  {id:'village',group:'personal',title:'A Life in Little Places',category:'Interactive portfolio',year:'08',label:'This website',image:'village-open-meadows.webp',summary:'A portfolio imagined as a mountain village that visitors can wander through.',role:'Concept, art direction & interaction',format:'Interactive web experience',question:'What if a portfolio felt like visiting someone rather than scrolling through a list?',intro:'The village gives writing, selected work, photographs, learning, experiments, and contact their own places. Visitors choose a path, enter rooms, and discover the work through objects.',decisions:[['Start with a sense of place','The mountain setting gives every part of the portfolio a shared home and visual language.'],['Let curiosity lead','Dots, labels, rooms, and the small character reward exploration while the Places menu keeps navigation direct.'],['Keep the world alive','The bus, flags, clouds, smoke, petals, fog, and sound add atmosphere without turning the scene into a busy simulation.']],reflection:'This remains a living portfolio. Its structure can grow as new work, writing, and photographs arrive.'}
 ],
 albums: [
  {id:'roads',title:'Mountains & roads',subtitle:'Three ways of looking outward',cover:'photos/mountains.jpg',description:'Peaks, movement, and the color of a passing street.',photos:[
   {image:'photos/mountains.jpg',title:'Blue above the snowline',caption:'Snow-covered mountains beneath a vivid blue sky.',position:'50% 48%'},
   {image:'photos/street.jpg',title:'Passing color',caption:'A green and yellow auto-rickshaw moving past a painted storefront.',position:'50% 50%'},
   {image:'photos/pavilion.jpg',title:'Above the city',caption:'A silhouetted domed pavilion against the skyline.',position:'50% 55%'}]},
  {id:'architecture',title:'Places & passages',subtitle:'Courtyards, screens & monuments',cover:'photos/courtyard.jpg',description:'Architecture seen through movement, shadow, and framing.',photos:[
   {image:'photos/courtyard.jpg',title:'Geometry in the courtyard',caption:'People and long shadows crossing a geometric courtyard.',position:'50% 52%'},
   {image:'photos/taj-mahal.jpg',title:'Between the trees',caption:'The Taj Mahal framed by trees beneath a dramatic sky.',position:'50% 44%'},
   {image:'photos/gateway.jpg',title:'Through the stone screen',caption:'A courtyard and gateway seen through an ornate stone screen.',position:'50% 50%'}]},
  {id:'water',title:'Water & distance',subtitle:'Boats, reflections & morning haze',cover:'photos/boat.jpg',description:'Quiet frames where water carries most of the light.',photos:[
   {image:'photos/boat.jpg',title:'Still water',caption:'A person in a small boat reflected on a calm surface.',position:'50% 50%'},
   {image:'photos/morning-haze.jpg',title:'Into the morning',caption:'Rowboats and birds emerging through bright haze.',position:'50% 50%'},
   {image:'photos/rowboats.jpg',title:'Three boats',caption:'Three rowboats moving across misty water.',position:'50% 48%'}]}
 ]
};
