window.villageRooms = {
 tea:{image:'tea-house-simple.webp',eyebrow:'Make yourself at home',description:'Pull up a cushion. Open a notebook.',objects:[{name:'The bookshelf',detail:'Essays & reflections',x:13,y:39,action:'shelf',value:'essays'},{name:'The open notebook',detail:'Notes along the way',x:63,y:61,action:'shelf',value:'notes'},{name:'Pour a cup',detail:'Take your time',x:73,y:62,action:'tea'}]},
 monastery:{image:'monastery.webp',eyebrow:'A quiet place to stay curious',description:'A few ideas to sit with.',objects:[{name:'The reading shelf',detail:'Things I’m learning',x:12,y:51,action:'item',value:0},{name:'The study table',detail:'A beginner, again',x:81,y:64,action:'item',value:1}]},
 studio:{image:'studio.webp',eyebrow:'Inside the design studio',description:'From a first question to the final detail.',objects:[{name:'The project board',detail:'Browse selected work',x:15,y:46,action:'projects'},{name:'The work desk',detail:'An idea called Hillpost',x:92,y:47,action:'project',value:'hillpost'}]},
 projects:{image:'projects.webp',eyebrow:'Give small ideas room to grow',description:'Some experiments are just taking root.',objects:[{name:'The little village',detail:'An interactive experiment',x:94,y:53,action:'project',value:'village'},{name:'The seed tray',detail:'What’s growing next',x:10,y:49,action:'item',value:1}]},
 skills:{image:'skills.webp',eyebrow:'Inside the workshop',description:'Well-used tools. New possibilities.',objects:[{name:'The workbench',detail:'Design & making',x:17,y:54,action:'item',value:0},{name:'The sketchbook',detail:'Working together',x:88,y:49,action:'item',value:1}]},
 trail:{image:'trail.webp',eyebrow:'A pause along the forest trail',description:'Small observations, kept for later.',objects:[{name:'The field journal',detail:'Notes from a walk',x:87,y:52,action:'item',value:0},{name:'The photo albums',detail:'Through the viewfinder',x:16,y:31,action:'albums'}]},
 contact:{image:'contact.webp',eyebrow:'The village post office',description:'Good conversations start with hello.',objects:[{name:'The writing desk',detail:'Leave a letter',x:75,y:49,action:'letter'},{name:'The service bell',detail:'Anyone home?',x:87,y:51,action:'bell'}]}
};
