window.villageRooms = {
 tea:{image:'tea-house-simple.webp',eyebrow:'Make yourself at home',description:'Pull up a cushion. Open a notebook.',objects:[{name:'The bookshelf',detail:'Essays & reflections',x:13,y:39,action:'shelf',value:'essays'},{name:'The open notebook',detail:'Notes along the way',x:63,y:61,action:'shelf',value:'notes'},{name:'Pour a cup',detail:'Take your time',x:73,y:62,action:'tea'}]},
 monastery:{image:'monastery.webp',eyebrow:'A quiet place to stay curious',description:'Books, notes, and ideas worth returning to.',objects:[{name:'The reading shelf',detail:'Books & influences',x:12,y:51,action:'item',value:0},{name:'The study table',detail:'A useful learning practice',x:81,y:64,action:'item',value:1}]},
 studio:{image:'studio.webp',eyebrow:'Inside the design studio',description:'Public platforms and complex systems.',objects:[{name:'The project board',detail:'Browse selected work',x:15,y:46,action:'projects'},{name:'The work desk',detail:'Lakshadweep ticketing',x:92,y:47,action:'project',value:'lakshadweep'}]},
 projects:{image:'projects.webp',eyebrow:'Give small ideas room to grow',description:'Experiments, prototypes, and working concepts.',objects:[{name:'The greenhouse table',detail:'Browse personal projects',x:10,y:49,action:'projects'},{name:'The little village',detail:'This interactive portfolio',x:94,y:53,action:'project',value:'village'}]},
 skills:{image:'skills.webp',eyebrow:'Inside the workshop',description:'Product thinking, craft, prototypes, and collaboration.',objects:[{name:'The workbench',detail:'Product design & making',x:17,y:54,action:'item',value:0},{name:'The sketchbook',detail:'Working across teams',x:88,y:49,action:'item',value:1}]},
 trail:{image:'trail.webp',eyebrow:'A pause along the forest trail',description:'Nine photographs from roads, places, and water.',objects:[{name:'The field journal',detail:'Through the viewfinder',x:87,y:52,action:'item',value:0},{name:'The photo albums',detail:'Open the collection',x:16,y:31,action:'albums'}]},
 contact:{image:'contact.webp',eyebrow:'The village post office',description:'Good conversations start with hello.',objects:[{name:'The writing desk',detail:'Leave a letter',x:75,y:49,action:'letter'},{name:'The service bell',detail:'Anyone home?',x:87,y:51,action:'bell'}]}
};
